sudo: false
language: python
cache: pip

python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
- pypy
- pypy-5.3.1

matrix:
  allow_failures:
  - python: pypy
  - python: pypy-5.3.1

before_install:
- pip install -U setuptools wheel

install:
- pip install .

script:
- python setup.py test

after_script:
- codecov

notifications:
  email:
  - althonosdev@gmail.com
